project:
  type: website
  output-dir: docs

website:
  title: "Rikki Adams"
  navbar:
    right: # accepts right/left/center; you can also place items individually on the left, right, and center
      - href: index.qmd
        text: Home
      - icon: github # add icons as navbar buttons
        href: https://rikada.github.io/rikada/
        target: _blank

# additional metadata excluded for brevity ~

format:
  html:
    theme: 
      - cosmo
      - styles.scss
    toc: false
    page-layout: full