project:
  type: website

website:
  title: "Rikki Adams"
  navbar:
    right:
      - icon: house
        href: index.qmd
        text: Home
      - icon: hammer
        href: projects.qmd
        text: Projects

format:
  html:
    theme: styles.scss
    mainfont: Ubuntu
    toc: true
 
    # ~ additional YAML excluded for brevity ~
links: 
    - icon: linkedin 
      text: LinkedIn
      href: https://www.linkedin.com/in/RikkiAdams/
      target: _blank