---
title: "Rikki Adams"
toc: false
about:
  template: trestles
  links:
    - text: GitHub
      href: https://rikada.github.io/rikada/
    - text: Email
      href: link
---

::: {.column-page}

## Bio
My name is Rikki Adams. I am a Second-Year Graduate Student in Elizabeth Finn's Lab
at OMRF. I have broad interests in science, spanning from plant pathology to cancer
cell biology! Outside of science, I am an avid reader and a musician that plays 3 instruments :)

## Research Goals
In Finn Lab, we study genome organization! With the use of DNA Fluorescence in situ Hybridization, we measure spot pair distances to obtain radial position and 3D measurements. My research goals include working with my current and different cell lines and optimize DNA FISH in those cell lines to answer the central question of my project!

## Experience
As I have mentioned, I have a broad spectrum of experience in science. I have been a tutor for several different subject in Biology, including Microbiology, Ecology, and Anatomy and Physiology. I have worked as a Lab Assistant for Microbiology and Biology at Oklahoma City Community College. I worked with Dr. Elizabeth Finn as a Post-Bacc and then now as a Graduate Student, studying genome organization

:::